import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google"
import { MainLayoutLogo } from "@/src/components/MainLayoutLogo"
import "@/src/app/globals.css"
import { ClerkProvider } from '@clerk/nextjs';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
          
          <header className="absolute top-0 left-0 w-1/2 h-20 flex items-center pr-6 pt-2">
            <div className="max-w-7xl w-full p-4 flex items-center justify-start">
              <MainLayoutLogo />
              {/* Add any additional header content here */}
            </div>
          </header>
          <main>
            {children}
          </main>
      </body>
    </html>
    </ClerkProvider>
  );
}