import { DashboardSidebar } from "@/src/components/students/StudentSidebarLeft"
import "@/src/app/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen md:flex">
        {/* Sidebar */}
        <DashboardSidebar />

        {/* Main content */}
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}

